"""Shared wire model + per-binding codec generation (#lzwiremodel)."""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import wire_codegen  # noqa: E402
from wire_codegen import UnsupportedSchema  # noqa: E402

RECEIPTS = json.loads((ROOT / "schemas" / "receipts.json").read_text())


def _surface(schema: dict) -> dict:
    surface = wire_codegen._SurfaceBuilder("t", "schemas/t.json", schema).build()
    surface["model_sha256"] = wire_codegen.surface_digest(surface)
    return surface


def _types(surface: dict) -> dict[str, dict]:
    return {t["name"]: t for t in surface["types"]}


def test_golden_model_matches_schemas() -> None:
    golden = (ROOT / "codegen" / "wire-model.json").read_text()
    assert golden == wire_codegen.render_model(wire_codegen.build_model())


def test_receipts_model_carries_the_wire_shapes() -> None:
    types = _types(_surface(RECEIPTS))
    assert [t["name"] for t in _surface(RECEIPTS)["types"]] == [
        "ReceiptOutcome",
        "CausalReceipt",
        "CausalReceipts",
        "ReceiptMessage",
    ]
    fields = {f["name"]: f for f in types["CausalReceipt"]["fields"]}
    assert fields["generation"]["type"] == {"kind": "u64"}
    # Required-and-nullable: always on the wire, null when absent.
    assert fields["reason"]["presence"] == "required"
    assert fields["reason"]["type"] == {"kind": "nullable", "inner": {"kind": "string"}}
    assert fields["outcome"]["type"] == {"kind": "ref", "name": "ReceiptOutcome"}
    assert [v["wire"] for v in types["ReceiptOutcome"]["values"]] == [
        "observed",
        "accepted",
        "applied",
        "rejected",
    ]
    assert types["ReceiptOutcome"]["open"] is False
    assert types["ReceiptMessage"]["variants"] == [{"tag": "CausalReceipts", "type": "CausalReceipts"}]


def test_model_digest_moves_with_any_schema_change() -> None:
    edited = copy.deepcopy(RECEIPTS)
    edited["$defs"]["CausalReceipt"]["properties"]["observer"]["description"] = "changed"
    assert _surface(edited)["model_sha256"] != _surface(RECEIPTS)["model_sha256"]


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (lambda s: s["$defs"]["CausalReceipt"]["properties"]["generation"].pop("minimum"), "non-negative"),
        (lambda s: s["$defs"]["CausalReceipt"].pop("additionalProperties"), "closed"),
        (lambda s: s["$defs"]["ReceiptOutcome"]["x-lazily-enum-docs"].pop("applied"), "x-lazily-enum-docs"),
        (lambda s: s["$defs"]["ReceiptOutcome"]["x-lazily-enum-docs"].update(done="x"), "not in the enum"),
        (lambda s: s["$defs"]["CausalReceipt"]["properties"]["observer"].pop("description"), "description"),
        (lambda s: s["$defs"]["CausalReceipt"]["properties"].update(extra={"type": "number", "description": "x"}), "unsupported type"),
        (
            lambda s: s["$defs"]["CausalReceipt"]["properties"].update(
                bad={"$ref": "https://lazily.dev/schemas/defs.json#/$defs/X", "description": "x"}
            ),
            "local",
        ),
    ],
)
def test_unlowerable_schema_fails_closed(mutate, message: str) -> None:
    schema = copy.deepcopy(RECEIPTS)
    mutate(schema)
    with pytest.raises(UnsupportedSchema, match=message):
        _surface(schema)


def test_optional_fields_are_modelled_but_not_yet_lowered() -> None:
    schema = copy.deepcopy(RECEIPTS)
    schema["$defs"]["CausalReceipt"]["required"].remove("reason")
    surface = _surface(schema)
    reason = next(f for f in _types(surface)["CausalReceipt"]["fields"] if f["name"] == "reason")
    assert reason["presence"] == "optional"
    for render in wire_codegen.BACKENDS.values():
        with pytest.raises(UnsupportedSchema, match="optional"):
            render(surface, {"package": "lazily"})


def test_rust_backend_lowering() -> None:
    out = wire_codegen.render_rust(_surface(RECEIPTS), {})
    assert out.startswith("// @generated by lazily-spec")
    assert '#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]' in out
    assert "    pub generation: u64,\n" in out
    assert "    pub reason: Option<String>,\n" in out
    assert "    pub receipts: Vec<CausalReceipt>,\n" in out
    assert "    CausalReceipts(CausalReceipts),\n" in out


def test_rust_backend_renames_variants_that_do_not_round_trip() -> None:
    schema = copy.deepcopy(RECEIPTS)
    outcome = schema["$defs"]["ReceiptOutcome"]
    outcome["enum"] = ["observed", "okHTTP"]
    outcome["x-lazily-enum-docs"] = {"observed": "a", "okHTTP": "b"}
    out = wire_codegen.render_rust(_surface(schema), {})
    assert "rename_all" not in out
    assert 'serde(rename = "okHTTP")' in out
    assert "    OkHTTP,\n" in out


def test_wire_names_that_are_not_identifiers_fail_closed() -> None:
    schema = copy.deepcopy(RECEIPTS)
    outcome = schema["$defs"]["ReceiptOutcome"]
    outcome["enum"] = ["observed", "HTTP-ok"]
    outcome["x-lazily-enum-docs"] = {"observed": "a", "HTTP-ok": "b"}
    for render in wire_codegen.BACKENDS.values():
        with pytest.raises(UnsupportedSchema, match="identifier"):
            render(_surface(schema), {"package": "lazily"})


def test_go_backend_lowering() -> None:
    out = wire_codegen.render_go(_surface(RECEIPTS), {"package": "lazily"})
    assert out.startswith("// Code generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.\n")
    assert "\npackage lazily\n" in out
    assert '\tGeneration uint64 `json:"generation"`\n' in out
    assert '\tReason *string `json:"reason"`\n' in out
    assert "func (v *ReceiptOutcome) UnmarshalJSON(b []byte) error {" in out
    # Required lists never marshal as null.
    assert "\t\tw.Receipts = []CausalReceipt{}\n" in out
    # Envelopes are not lowered for Go.
    assert "ReceiptMessage" not in out


def test_check_reports_sibling_drift(tmp_path, monkeypatch, capsys) -> None:
    for repo in ("lazily-rs", "lazily-go"):
        (tmp_path / repo).mkdir()
    monkeypatch.setattr(wire_codegen, "WORKSPACE_SRC", tmp_path)
    assert wire_codegen.main(["--check"]) == 1
    assert "drift: receipts:rust" in capsys.readouterr().err

    model = wire_codegen.build_model()
    for _label, _repo, dest, content in wire_codegen.generated_targets(
        model, wire_codegen.load_manifest(), tmp_path
    ):
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)
    assert wire_codegen.main(["--check"]) == 0

    go_file = tmp_path / "lazily-go" / "receipts_wire_gen.go"
    go_file.write_text(go_file.read_text().replace("uint64", "int64"))
    assert wire_codegen.main(["--check"]) == 1
    assert "drift: receipts:go" in capsys.readouterr().err


def test_check_reports_absent_siblings_as_staged(tmp_path, monkeypatch, capsys) -> None:
    monkeypatch.setattr(wire_codegen, "WORKSPACE_SRC", tmp_path)
    assert wire_codegen.main(["--check"]) == 0
    assert "staged: receipts:rust" in capsys.readouterr().out
    assert wire_codegen.main(["--check", "--require-all"]) == 1
