"""Shared wire model + per-binding codec generation (#lzwiremodel)."""

from __future__ import annotations

import copy
import json
import re
import sys
import types
from pathlib import Path

import pytest

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import wire_codegen  # noqa: E402
from wire_codegen import UnsupportedSchema  # noqa: E402

RECEIPTS = json.loads((ROOT / "schemas" / "receipts.json").read_text())


def _surface(schema: dict) -> dict:
    surface = wire_codegen._SurfaceBuilder("t", "schemas/t.json", schema).build()
    surface["model_sha256"] = wire_codegen.surface_digest(surface)
    return surface


def _types(surface: dict) -> dict[str, dict]:
    return {t["name"]: t for t in surface["types"]}


def test_golden_model_matches_schemas() -> None:
    golden = (ROOT / "codegen" / "wire-model.json").read_text()
    assert golden == wire_codegen.render_model(wire_codegen.build_model())


def test_receipts_model_carries_the_wire_shapes() -> None:
    types = _types(_surface(RECEIPTS))
    assert [t["name"] for t in _surface(RECEIPTS)["types"]] == [
        "ReceiptOutcome",
        "CausalReceipt",
        "CausalReceipts",
        "ReceiptMessage",
    ]
    fields = {f["name"]: f for f in types["CausalReceipt"]["fields"]}
    assert fields["generation"]["type"] == {"kind": "u64"}
    # Required-and-nullable: always on the wire, null when absent.
    assert fields["reason"]["presence"] == "required"
    assert fields["reason"]["type"] == {"kind": "nullable", "inner": {"kind": "string"}}
    assert fields["outcome"]["type"] == {"kind": "ref", "name": "ReceiptOutcome"}
    assert [v["wire"] for v in types["ReceiptOutcome"]["values"]] == [
        "observed",
        "accepted",
        "applied",
        "rejected",
    ]
    assert types["ReceiptOutcome"]["open"] is False
    assert types["ReceiptMessage"]["variants"] == [{"tag": "CausalReceipts", "type": "CausalReceipts"}]


def test_model_digest_moves_with_any_schema_change() -> None:
    edited = copy.deepcopy(RECEIPTS)
    edited["$defs"]["CausalReceipt"]["properties"]["observer"]["description"] = "changed"
    assert _surface(edited)["model_sha256"] != _surface(RECEIPTS)["model_sha256"]


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (lambda s: s["$defs"]["CausalReceipt"]["properties"]["generation"].pop("minimum"), "non-negative"),
        (lambda s: s["$defs"]["CausalReceipt"].pop("additionalProperties"), "closed"),
        (lambda s: s["$defs"]["ReceiptOutcome"]["x-lazily-enum-docs"].pop("applied"), "x-lazily-enum-docs"),
        (lambda s: s["$defs"]["ReceiptOutcome"]["x-lazily-enum-docs"].update(done="x"), "not in the enum"),
        (lambda s: s["$defs"]["CausalReceipt"]["properties"]["observer"].pop("description"), "description"),
        (lambda s: s["$defs"]["CausalReceipt"]["properties"].update(extra={"type": "number", "description": "x"}), "unsupported type"),
        (
            lambda s: s["$defs"]["CausalReceipt"]["properties"].update(
                bad={"$ref": "https://example.com/schemas/other.json#/$defs/X", "description": "x"}
            ),
            "only local",
        ),
        (
            lambda s: s["$defs"]["CausalReceipt"]["properties"].update(
                bad={"$ref": "https://lazily.dev/schemas/defs.json#/$defs/X", "description": "x"}
            ),
            "unresolved",
        ),
    ],
)
def test_unlowerable_schema_fails_closed(mutate, message: str) -> None:
    schema = copy.deepcopy(RECEIPTS)
    mutate(schema)
    with pytest.raises(UnsupportedSchema, match=message):
        _surface(schema)


def test_optional_fields_are_modelled_but_not_yet_lowered() -> None:
    schema = copy.deepcopy(RECEIPTS)
    schema["$defs"]["CausalReceipt"]["required"].remove("reason")
    surface = _surface(schema)
    reason = next(f for f in _types(surface)["CausalReceipt"]["fields"] if f["name"] == "reason")
    assert reason["presence"] == "optional"
    for backend, render in wire_codegen.BACKENDS.items():
        if backend == "python":
            continue
        with pytest.raises(UnsupportedSchema, match="optional"):
            render(surface, {"package": "lazily"})
    # Python lowers a may-be-absent field: omitted when None, absent or null on decode.
    out = wire_codegen.render_python(surface, PY_TARGET)
    assert '        if self.reason is not None:\n            body["reason"] = self.reason\n' in out
    assert 'reason=None if d.get("reason") is None else _wire_str("CausalReceipt.reason", d.get("reason")),' in out


def test_rust_backend_lowering() -> None:
    out = wire_codegen.render_rust(_surface(RECEIPTS), {})
    assert out.startswith("// @generated by lazily-spec")
    assert '#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]' in out
    assert "    pub generation: u64,\n" in out
    assert "    pub reason: Option<String>,\n" in out
    assert "    pub receipts: Vec<CausalReceipt>,\n" in out
    assert "    CausalReceipts(CausalReceipts),\n" in out
    # Closed records reject unknown keys; required-nullable fields reject a missing key.
    assert out.count('serde(deny_unknown_fields)') == 2
    assert out.count('serde(deserialize_with = "required_nullable")') == 2
    assert "fn required_nullable<'de, D, T>" in out


def test_rust_backend_renames_variants_that_do_not_round_trip() -> None:
    schema = copy.deepcopy(RECEIPTS)
    outcome = schema["$defs"]["ReceiptOutcome"]
    outcome["enum"] = ["observed", "okHTTP"]
    outcome["x-lazily-enum-docs"] = {"observed": "a", "okHTTP": "b"}
    out = wire_codegen.render_rust(_surface(schema), {})
    assert "rename_all" not in out
    assert 'serde(rename = "okHTTP")' in out
    assert "    OkHTTP,\n" in out


def test_wire_names_that_are_not_identifiers_fail_closed() -> None:
    schema = copy.deepcopy(RECEIPTS)
    outcome = schema["$defs"]["ReceiptOutcome"]
    outcome["enum"] = ["observed", "HTTP-ok"]
    outcome["x-lazily-enum-docs"] = {"observed": "a", "HTTP-ok": "b"}
    for render in wire_codegen.BACKENDS.values():
        with pytest.raises(UnsupportedSchema, match="identifier"):
            render(_surface(schema), {"package": "lazily"})


def test_go_backend_lowering() -> None:
    out = wire_codegen.render_go(_surface(RECEIPTS), {"package": "lazily"})
    assert out.startswith("// Code generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.\n")
    assert "\npackage lazily\n" in out
    assert '\tGeneration uint64 `json:"generation"`\n' in out
    assert '\tReason *string `json:"reason"`\n' in out
    assert "func (v *ReceiptOutcome) UnmarshalJSON(b []byte) error {" in out
    # Required lists never marshal as null.
    assert "\t\tw.Receipts = []CausalReceipt{}\n" in out
    # Envelopes are not lowered for Go.
    assert "ReceiptMessage" not in out
    # Records decode strictly: exact key set, case-sensitive.
    assert "func (r *CausalReceipt) UnmarshalJSON(data []byte) error {" in out
    # The helper is named per surface (here `t`) so several generated files share a package.
    assert "func tCheckWireFields(name string, data []byte, fields []string) error {" in out
    assert '"reason", "payload_hash"}); err != nil {' in out.replace("\n", "")


PY_TARGET = {
    "semantics_module": "._receipt_semantics",
    "mixins": {"ReceiptOutcome": "ReceiptOutcomeSemantics", "CausalReceipts": "CausalReceiptsSemantics"},
}


def _exec_python(out: str) -> dict:
    """Execute generated Python with stand-in semantics mixins."""
    module = out.replace(
        "from ._receipt_semantics import CausalReceiptsSemantics, ReceiptOutcomeSemantics\n",
        "class CausalReceiptsSemantics:\n    __slots__ = ()\n\n\nclass ReceiptOutcomeSemantics:\n    __slots__ = ()\n",
    )
    generated = types.ModuleType("receipts_gen")
    sys.modules[generated.__name__] = generated
    try:
        exec(compile(module, "<generated>", "exec"), generated.__dict__)
    finally:
        del sys.modules[generated.__name__]
    return generated.__dict__


def test_python_backend_lowering() -> None:
    out = wire_codegen.render_python(_surface(RECEIPTS), PY_TARGET)
    assert out.startswith("# @generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.\n")
    assert "class ReceiptOutcome(ReceiptOutcomeSemantics, Enum):" in out
    assert "class CausalReceipts(CausalReceiptsSemantics):" in out
    assert "    reason: str | None = None\n" in out
    assert "    receipts: list[CausalReceipt] = field(default_factory=list)\n" in out
    # The envelope lowers onto its single variant record.
    assert 'return {"CausalReceipts": body}' in out
    assert "class ReceiptMessage" not in out


def test_python_backend_decodes_strictly() -> None:
    ns = _exec_python(wire_codegen.render_python(_surface(RECEIPTS), PY_TARGET))
    receipt = {
        "receipt_id": "r",
        "causation_id": "c",
        "observer": "o",
        "generation": 1,
        "outcome": "applied",
        "reason": None,
        "payload_hash": None,
    }
    frame = {"CausalReceipts": {"receipts": [receipt]}}
    assert ns["CausalReceipts"].from_wire(frame).to_wire() == frame
    for bad, message in [
        ({k: v for k, v in receipt.items() if k != "reason"}, "missing field 'reason'"),
        ({**receipt, "extra": 1}, "unknown field 'extra'"),
        ({**receipt, "generation": -1}, "generation must be in"),
        ({**receipt, "generation": True}, "unsigned integer"),
        ({**receipt, "outcome": "done"}, "unknown ReceiptOutcome"),
    ]:
        with pytest.raises(ValueError, match=message):
            ns["CausalReceipt"].from_wire(bad)


def test_python_backend_rejects_mixins_for_unknown_types() -> None:
    with pytest.raises(UnsupportedSchema, match="mixins"):
        wire_codegen.render_python(_surface(RECEIPTS), {"semantics_module": ".x", "mixins": {"Nope": "X"}})


# ---------------------------------------------------------------------------
# Delta surface (#lzwiremodel4): unions, aliases, bytes, shared defs.json refs
# ---------------------------------------------------------------------------

DELTA = json.loads((ROOT / "schemas" / "delta.json").read_text())


def _delta_surface(schema: dict | None = None) -> dict:
    surface = wire_codegen._SurfaceBuilder("delta", "schemas/delta.json", schema or DELTA, ROOT).build()
    surface["model_sha256"] = wire_codegen.surface_digest(surface)
    return surface


def test_delta_model_carries_unions_aliases_and_shared_defs() -> None:
    types = _types(_delta_surface())
    op = types["DeltaOp"]
    assert op["kind"] == "union"
    assert [v["tag"] for v in op["variants"]] == [
        "CellSet", "SlotValue", "Invalidate", "NodeAdd", "NodeRemove",
        "EdgeAdd", "EdgeRemove", "QueuePush", "QueuePop", "QueueClose",
    ]
    assert {v["tag"]: v["payload"] for v in op["variants"]}["QueuePush"] == {"kind": "ref", "name": "CellSetBody"}
    # Shared defs.json declarations are pulled in transitively.
    assert types["IpcValue"]["variants"][0] == {
        "tag": "Inline",
        "doc": "Inline serialized bytes as JSON array of u8 (NOT base64).",
        "payload": {"kind": "bytes"},
    }
    assert types["NodeState"]["variants"][2]["payload"] is None  # unit variant "Opaque"
    assert types["NodeId"] == {
        "name": "NodeId", "kind": "alias", "doc": types["NodeId"]["doc"], "target": {"kind": "u64"},
    }
    assert types["NodeKey"]["target"] == {
        "kind": "string", "min_length": 1, "max_length": 1024, "pattern": "^[^/]+(/[^/]+)*$",
    }
    key = next(f for f in types["NodeAddBody"]["fields"] if f["name"] == "key")
    assert key["presence"] == "optional"
    assert key["type"] == {"kind": "nullable", "inner": {"kind": "ref", "name": "NodeKey"}}
    backend = next(f for f in types["ShmBlobRef"]["fields"] if f["name"] == "backend")
    assert backend["default"] == "shm"
    assert backend["type"] == {"kind": "ref", "name": "BlobBackendKind"}
    assert [v["wire"] for v in types["BlobBackendKind"]["values"]] == ["shm", "arrow", "in_process"]


def test_delta_lowers_only_into_python_go_and_kotlin_so_far() -> None:
    surface = _delta_surface()
    for backend, render in wire_codegen.BACKENDS.items():
        if backend in ("python", "go", "kotlin"):
            continue
        with pytest.raises(UnsupportedSchema, match="modelled but not yet lowered"):
            render(surface, {"package": "p"})
    # Each union path needs the target to name each non-record variant payload's field.
    with pytest.raises(UnsupportedSchema, match="variant_fields"):
        wire_codegen.render_python(surface, {})
    with pytest.raises(UnsupportedSchema, match="variant_fields"):
        wire_codegen.render_go(surface, {"package": "p"})
    with pytest.raises(UnsupportedSchema, match="variant_fields"):
        wire_codegen.render_kotlin(surface, {"package": "p"})


def _delta_go_target() -> dict:
    manifest = json.loads((ROOT / "codegen" / "surfaces.json").read_text())
    entry = next(s for s in manifest["surfaces"] if s["name"] == "delta")
    return entry["targets"]["go"]


def test_go_backend_union_lowering() -> None:
    out = wire_codegen.render_go(_delta_surface(), _delta_go_target())
    assert out.startswith("// Code generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.\n")
    # A union is an interface plus one struct per variant, with any hand-written
    # methods the target declares.
    assert "type DeltaOp interface {\n\tjson.Marshaler\n" in out
    assert "\tTargetReadable(permissions *PeerPermissions, peer PeerId) bool\n\tisDeltaOp()\n}" in out
    assert "func unmarshalDeltaOp(raw json.RawMessage) (DeltaOp, error) {" in out
    # Record payloads are flattened; other payloads take their target-named field.
    assert "type DeltaOpCellSet struct {\n\t// Node: Target node.\n\tNode NodeId\n" in out
    assert "type IpcValueInline struct {\n\tBytes []byte\n}" in out
    assert "type NodeStateOpaque struct{}" in out
    # u64 held in a hand-written signed type is range-checked both ways.
    assert 'fNode, err := deltaWireInt64("DeltaOp.CellSet.node", f["node"])' in out
    assert 'deltaWireCheckInt64("Delta.base_epoch", r.BaseEpoch)' in out
    # An optional field is a pointer, omitted when nil and read as absent from null.
    assert "\tKey *NodeKey\n" in out
    assert 'if raw, ok := f["key"]; ok && !deltaWireIsNull(raw) {' in out


def test_go_union_lowering_refuses_an_unmapped_alias() -> None:
    target = dict(_delta_go_target())
    target["int64"] = {k: v for k, v in target["int64"].items() if k != "NodeId"}
    with pytest.raises(UnsupportedSchema, match="alias NodeId needs an `int64` mapping"):
        wire_codegen.render_go(_delta_surface(), target)


def _delta_kt_target() -> dict:
    manifest = json.loads((ROOT / "codegen" / "surfaces.json").read_text())
    entry = next(s for s in manifest["surfaces"] if s["name"] == "delta")
    return entry["targets"]["kotlin"]


def test_kotlin_backend_union_lowering() -> None:
    out = wire_codegen.render_kotlin(_delta_surface(), _delta_kt_target())
    assert out.startswith("// @generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.\n")
    # u64 is not on this path: nothing needs the experimental ULong opt-in.
    assert "@file:OptIn" not in out
    # Every refusal goes through the target's decode error, so one catch covers all.
    assert "private fun deltaWireFail(message: String): Nothing = throw IpcDecodeException.Malformed(message)" in out
    assert "throw IllegalArgumentException" not in out
    # A union is a sealed interface, one data class per variant, record payloads
    # flattened, and a companion on each class for hand-written factories.
    assert "sealed interface DeltaOp {\n    /** Encode the externally-tagged wire form. */\n    fun toJson(): JsonObject\n" in out
    assert "    data class CellSet(\n        /** Target node. */\n        val node: NodeId,\n" in out
    assert "\n        companion object\n    }\n" in out
    # Non-record payloads take their target-named field; a ByteArray compares by content.
    assert "    data class Inline(\n        val bytes: ByteArray,\n    ) : IpcValue {" in out
    assert "override fun equals(other: Any?): Boolean = other is Inline && bytes.contentEquals(other.bytes)" in out
    # A unit variant is a data object encoding to the bare tag; the dict form is refused.
    assert '    data object Opaque : NodeState {\n        override fun toJson(): JsonElement = JsonPrimitive("Opaque")' in out
    assert '"Opaque" -> Opaque\n                    else -> deltaWireFail("NodeState: unknown unit variant' in out
    assert '"Opaque" -> deltaWireNodeState' not in out
    # u64 held in a hand-written signed type is range-checked both ways.
    assert 'node = deltaWireLong("DeltaOp.CellSet.node", obj.getValue("node")),' in out
    assert 'put("base_epoch", deltaWireLongJson("Delta.base_epoch", baseEpoch))' in out
    assert "exceeds this binding's range 0..=2^63-1" in out
    assert 'require(value >= 0) { "$name: $value is negative; the wire type is u64" }' in out
    # Strict objects: required and optional key lists, unknown keys refused.
    assert 'deltaWireObject("DeltaOp.NodeAdd", body, listOf("node", "type_tag", "state"), listOf("key"))' in out
    assert 'if (unknown != null) deltaWireFail("$name: unknown field' in out
    # An optional field defaults to null, reads null as absent, and is omitted on encode.
    assert "        val key: NodeKey? = null,\n" in out
    assert 'key = obj["key"]?.takeUnless { it is JsonNull }?.let { value -> NodeKey.fromJson(value) },' in out
    assert 'if (key != null) put("key", key.toJson())' in out
    # Externals keep their hand-written codecs and are not emitted.
    for name in ("NodeKey", "ShmBlobRef", "BlobBackendKind", "DeltaFrame", "typealias"):
        assert f"class {name}" not in out and f"interface {name}" not in out
    assert "typealias" not in out
    assert all(len(line) <= 120 for line in out.splitlines()[3:])


def test_kotlin_union_lowering_refuses_what_it_cannot_lower() -> None:
    target = copy.deepcopy(_delta_kt_target())
    target["int64"].pop("NodeId")
    with pytest.raises(UnsupportedSchema, match="alias NodeId needs an `int64` mapping"):
        wire_codegen.render_kotlin(_delta_surface(), target)
    target = copy.deepcopy(_delta_kt_target())
    target["int64"].pop("Delta.epoch")
    with pytest.raises(UnsupportedSchema, match="u64 Delta.epoch in a union surface needs an `int64` mapping"):
        wire_codegen.render_kotlin(_delta_surface(), target)
    target = copy.deepcopy(_delta_kt_target())
    target.pop("envelope")
    with pytest.raises(UnsupportedSchema, match="envelope DeltaFrame"):
        wire_codegen.render_kotlin(_delta_surface(), target)
    target = copy.deepcopy(_delta_kt_target())
    target["external"].pop("ShmBlobRef")
    # Without `external`, ShmBlobRef's defaulted `backend` fails closed.
    with pytest.raises(UnsupportedSchema, match="field defaults are modelled but not yet lowered"):
        wire_codegen.render_kotlin(_delta_surface(), target)
    # A decode error with a long name can push a generated line past ktlint's limit.
    target = copy.deepcopy(_delta_kt_target())
    target["decode_error"] = "a." * 60 + "E"
    with pytest.raises(UnsupportedSchema, match="120 columns"):
        wire_codegen.render_kotlin(_delta_surface(), target)


def test_kotlin_receipts_keep_the_record_path() -> None:
    # Receipts have no union, so the union path must not touch their output.
    out = wire_codegen.render_kotlin(_surface(RECEIPTS), KT_TARGET)
    assert "@file:OptIn(ExperimentalSerializationApi::class)" in out
    assert "deltaWire" not in out and "Fail(" not in out


def _op_branch(schema: dict, tag: str) -> dict:
    return next(b for b in schema["$defs"]["DeltaOp"]["oneOf"] if b.get("title") == tag)


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (lambda s: _op_branch(s, "CellSet").update(required=[]), "must require its tag"),
        (lambda s: _op_branch(s, "CellSet").update(title="Other"), "differs from tag"),
        (lambda s: _op_branch(s, "CellSet").pop("additionalProperties"), "must be closed"),
        (lambda s: _op_branch(s, "CellSet").pop("description"), "description"),
        (lambda s: s["$defs"]["DeltaOp"]["oneOf"].append(copy.deepcopy(_op_branch(s, "CellSet"))), "distinct"),
        (lambda s: s["$defs"].update(NodeId={"type": "integer", "minimum": 0, "description": "x"}), "both locally"),
        (
            lambda s: s["$defs"]["NodeBody"]["properties"].update(
                extra={"type": "integer", "minimum": 0, "maximum": 7, "description": "x"}
            ),
            "maximum",
        ),
    ],
)
def test_unlowerable_union_shapes_fail_closed(mutate, message: str) -> None:
    schema = copy.deepcopy(DELTA)
    mutate(schema)
    with pytest.raises(UnsupportedSchema, match=message):
        _delta_surface(schema)


def test_a_root_the_model_would_skip_fails_closed() -> None:
    # Before #lzwiremodel4 a root that was not an x-lazily-envelope was skipped
    # silently: signaling.json "modelled" as zero types.
    schema = copy.deepcopy(DELTA)
    del schema["x-lazily-envelope"]
    with pytest.raises(UnsupportedSchema, match="not an x-lazily-envelope"):
        _delta_surface(schema)
    with pytest.raises(UnsupportedSchema, match="declares nothing"):
        wire_codegen._SurfaceBuilder("e", "schemas/e.json", {"$defs": {}}, ROOT).build()


def _model_accepts(types: dict, expr: dict, value) -> bool:
    """A strict reference reading of the model: does ``value`` conform to ``expr``?"""
    kind = expr["kind"]
    if kind == "string":
        return (
            isinstance(value, str)
            and expr.get("min_length", 0) <= len(value) <= expr.get("max_length", len(value))
            and ("pattern" not in expr or re.search(expr["pattern"], value) is not None)
        )
    if kind == "u64":
        return isinstance(value, int) and not isinstance(value, bool) and 0 <= value <= wire_codegen.U64_MAX
    if kind == "bool":
        return isinstance(value, bool)
    if kind == "bytes":
        return isinstance(value, list) and all(
            isinstance(b, int) and not isinstance(b, bool) and 0 <= b <= 255 for b in value
        )
    if kind == "list":
        return isinstance(value, list) and all(_model_accepts(types, expr["items"], v) for v in value)
    if kind == "nullable":
        return value is None or _model_accepts(types, expr["inner"], value)
    assert kind == "ref", kind
    t = types[expr["name"]]
    if t["kind"] == "alias":
        return _model_accepts(types, t["target"], value)
    if t["kind"] == "enum":
        return value in [v["wire"] for v in t["values"]]
    if t["kind"] == "record":
        if not isinstance(value, dict):
            return False
        fields = {f["name"]: f for f in t["fields"]}
        required = {n for n, f in fields.items() if f["presence"] == "required"}
        return (
            required <= set(value) <= set(fields)
            and all(_model_accepts(types, fields[k]["type"], v) for k, v in value.items())
        )
    if t["kind"] == "union":
        for variant in t["variants"]:
            if variant["payload"] is None:
                if value == variant["tag"]:
                    return True
            elif isinstance(value, dict) and list(value) == [variant["tag"]]:
                return _model_accepts(types, variant["payload"], value[variant["tag"]])
        return False
    assert t["kind"] == "envelope", t["kind"]
    if not isinstance(value, dict) or len(value) != 1:
        return False
    (tag, body), = value.items()
    match = [v for v in t["variants"] if v["tag"] == tag]
    return bool(match) and _model_accepts(types, {"kind": "ref", "name": match[0]["type"]}, body)


def _delta_frames() -> list[tuple[str, dict]]:
    """Every `{"Delta": {...}}` frame anywhere in the conformance corpus."""
    frames = []

    def walk(where: str, node) -> None:
        if isinstance(node, dict):
            if list(node) == ["Delta"] and isinstance(node["Delta"], dict):
                frames.append((where, node))
            for k, v in node.items():
                walk(f"{where}.{k}", v)
        elif isinstance(node, list):
            for i, v in enumerate(node):
                walk(f"{where}[{i}]", v)

    for path in sorted((ROOT / "conformance").rglob("*.json")):
        walk(str(path.relative_to(ROOT)), json.loads(path.read_text()))
    return frames


def _perturbations(frame: dict):
    """Off-schema (and on-schema) variants of one frame, each a single edit."""
    yield "as-is", frame
    body = frame["Delta"]
    for key in ("base_epoch", "epoch", "ops"):
        dropped = copy.deepcopy(frame)
        del dropped["Delta"][key]
        yield f"drop {key}", dropped
    extra = copy.deepcopy(frame)
    extra["Delta"]["extra"] = 1
    yield "unknown frame key", extra
    negative = copy.deepcopy(frame)
    negative["Delta"]["epoch"] = -1
    yield "negative epoch", negative
    for i, op in enumerate(body["ops"]):
        if not isinstance(op, dict) or len(op) != 1:
            continue
        (tag, op_body), = op.items()
        lower = copy.deepcopy(frame)
        lower["Delta"]["ops"][i] = {tag.lower(): op_body}
        yield f"op {i} lowercase tag", lower
        if isinstance(op_body, dict):
            unknown = copy.deepcopy(frame)
            unknown["Delta"]["ops"][i][tag]["extra"] = 1
            yield f"op {i} unknown body key", unknown
            for field in list(op_body):
                gone = copy.deepcopy(frame)
                del gone["Delta"]["ops"][i][tag][field]
                yield f"op {i} drop {field}", gone
            if "key" in op_body or tag == "NodeAdd":
                for key in (None, "", "a//b", "scores/alice"):
                    keyed = copy.deepcopy(frame)
                    keyed["Delta"]["ops"][i][tag]["key"] = key
                    yield f"op {i} key {key!r}", keyed
            if tag == "NodeAdd":
                for state in ("Opaque", "opaque", {"Payload": [1, 256]}, {"Payload": "AQ=="}):
                    stated = copy.deepcopy(frame)
                    stated["Delta"]["ops"][i][tag]["state"] = state
                    yield f"op {i} state {state!r}", stated
            payload = op_body.get("payload")
            if isinstance(payload, dict) and "SharedBlob" in payload:
                for backend in ("arrow", "rdma", None):
                    blob = copy.deepcopy(frame)
                    blob["Delta"]["ops"][i][tag]["payload"]["SharedBlob"]["backend"] = backend
                    yield f"op {i} backend {backend!r}", blob


def _delta_validator():
    from referencing import Registry
    from referencing.jsonschema import DRAFT202012

    jsonschema = pytest.importorskip("jsonschema")
    resources = [
        (f"https://lazily.dev/schemas/{n}.json", DRAFT202012.create_resource(json.loads((ROOT / "schemas" / f"{n}.json").read_text())))
        for n in ("defs", "delta")
    ]
    return jsonschema.Draft202012Validator(DELTA, registry=Registry().with_resources(resources))


def test_delta_model_agrees_with_schema_on_every_corpus_frame() -> None:
    """The model reads every corpus Delta frame, and single-edit perturbations of it,
    exactly as the JSON Schema does: what one accepts the other accepts."""
    validator = _delta_validator()
    surface = _delta_surface()
    types = _types(surface)
    frames = _delta_frames()
    assert len(frames) >= 20, f"expected a substantial Delta corpus, found {len(frames)}"
    tags_seen: set[str] = set()
    checked = accepted = 0
    disagreements = []
    for where, frame in frames:
        for label, candidate in _perturbations(frame):
            schema_ok = validator.is_valid(candidate)
            model_ok = _model_accepts(types, {"kind": "ref", "name": "DeltaFrame"}, candidate)
            checked += 1
            accepted += schema_ok
            if schema_ok != model_ok:
                disagreements.append(f"{where} [{label}]: schema={schema_ok} model={model_ok}")
        for op in frame["Delta"].get("ops", []):
            if isinstance(op, dict):
                tags_seen |= set(op)
    assert not disagreements, "\n".join(disagreements[:20])
    # Both verdicts occurred, so neither side is vacuously agreeing.
    assert 0 < accepted < checked
    # The corpus exercises every op tag the union declares except the two
    # queue ops it has never carried a frame for.
    declared = {v["tag"] for v in types["DeltaOp"]["variants"]}
    assert declared - tags_seen <= {"QueuePop", "QueueClose"}, declared - tags_seen


KT_TARGET = {"package": "io.github.lazily", "variant_fields": {"CausalReceipts": "batch"}}


def test_kotlin_backend_lowering() -> None:
    out = wire_codegen.render_kotlin(_surface(RECEIPTS), KT_TARGET)
    assert out.startswith("// @generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.\n")
    assert "\npackage io.github.lazily\n" in out
    # u64 lowers to ULong, so a negative generation is unrepresentable.
    assert "    val generation: ULong,\n" in out
    assert "    val reason: String? = null,\n" in out
    assert "    val receipts: List<CausalReceipt> = emptyList(),\n" in out
    # Required-nullable fields are always emitted, as `null` when absent.
    assert 'put("reason", reason?.let { JsonPrimitive(it) } ?: JsonNull)' in out
    # The envelope is lowered as a sealed interface; the variant field name comes from the target.
    assert "sealed interface ReceiptMessage {" in out
    assert "    data class CausalReceiptsMessage(\n        val batch: CausalReceipts,\n" in out
    # Strict decoding: exact key set, min_length checked at construction.
    assert 'val obj = receiptsWireObject("CausalReceipt", element, FIELDS)' not in out
    assert 'val obj = tWireObject("CausalReceipt", element, FIELDS)' in out
    assert 'require(receiptId.length >= 1) { "receipt_id must be a non-empty string" }' in out
    assert "@file:OptIn(ExperimentalSerializationApi::class)" in out


def test_kotlin_backend_default_variant_field_and_keywords() -> None:
    out = wire_codegen.render_kotlin(_surface(RECEIPTS), {"package": "p"})
    assert "        val value: CausalReceipts,\n" in out
    schema = copy.deepcopy(RECEIPTS)
    props = schema["$defs"]["CausalReceipt"]["properties"]
    props["in"] = {"type": "string", "description": "x"}
    schema["$defs"]["CausalReceipt"]["required"].append("in")
    with pytest.raises(UnsupportedSchema, match="keyword"):
        wire_codegen.render_kotlin(_surface(schema), {"package": "p"})


def test_check_reports_sibling_drift(tmp_path, monkeypatch, capsys) -> None:
    for repo in ("lazily-rs", "lazily-go", "lazily-py"):
        (tmp_path / repo).mkdir()
    monkeypatch.setattr(wire_codegen, "WORKSPACE_SRC", tmp_path)
    assert wire_codegen.main(["--check"]) == 1
    assert "drift: receipts:rust" in capsys.readouterr().err

    model = wire_codegen.build_model()
    for _label, _repo, dest, content in wire_codegen.generated_targets(
        model, wire_codegen.load_manifest(), tmp_path
    ):
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)
    assert wire_codegen.main(["--check"]) == 0

    go_file = tmp_path / "lazily-go" / "receipts_wire_gen.go"
    go_file.write_text(go_file.read_text().replace("uint64", "int64"))
    assert wire_codegen.main(["--check"]) == 1
    assert "drift: receipts:go" in capsys.readouterr().err


def test_check_reports_absent_siblings_as_staged(tmp_path, monkeypatch, capsys) -> None:
    monkeypatch.setattr(wire_codegen, "WORKSPACE_SRC", tmp_path)
    assert wire_codegen.main(["--check"]) == 0
    assert "staged: receipts:rust" in capsys.readouterr().out
    assert wire_codegen.main(["--check", "--require-all"]) == 1


# Stand-ins for the two hand-written externals, each reading its declaration
# exactly as the schema does, so a disagreement below is the GENERATED code's.
_DELTA_STUBS = '''
import re as _re


class DeltaOpSemantics:
    __slots__ = ()


class DeltaSemantics:
    __slots__ = ()


class IpcValueSemantics:
    __slots__ = ()


class NodeKey:
    def __init__(self, path):
        self.path = path

    @classmethod
    def from_wire(cls, value):
        if not isinstance(value, str) or not 1 <= len(value) <= 1024:
            raise ValueError("NodeKey")
        if _re.search(r"^[^/]+(/[^/]+)*$", value) is None:
            raise ValueError("NodeKey pattern")
        return cls(value)

    def to_wire(self):
        return self.path


class ShmBlobRef:
    _REQUIRED = ("offset", "len", "generation", "epoch", "checksum")

    def __init__(self, d):
        self.d = d

    @classmethod
    def from_wire(cls, d):
        if not isinstance(d, dict) or set(cls._REQUIRED) - set(d) or set(d) - {*cls._REQUIRED, "backend"}:
            raise ValueError("ShmBlobRef keys")
        for key in cls._REQUIRED:
            if isinstance(d[key], bool) or not isinstance(d[key], int) or not 0 <= d[key] < 2**64:
                raise ValueError("ShmBlobRef " + key)
        if "backend" in d and d["backend"] not in ("shm", "arrow", "in_process"):
            raise ValueError("ShmBlobRef backend")
        return cls(d)

    def to_wire(self):
        return dict(self.d)
'''


def _delta_py_target() -> dict:
    manifest = json.loads((ROOT / "codegen" / "surfaces.json").read_text())
    entry = next(s for s in manifest["surfaces"] if s["name"] == "delta")
    return entry["targets"]["python"]


def _exec_delta_python() -> dict:
    out = wire_codegen.render_python(_delta_surface(), _delta_py_target())
    for line in out.splitlines():
        if line.startswith("from ._"):
            out = out.replace(line + "\n", "")
    module = types.ModuleType("delta_gen")
    sys.modules[module.__name__] = module
    try:
        source = out.replace("from typing import Any\n", "from typing import Any\n" + _DELTA_STUBS, 1)
        exec(compile(source, "<generated delta>", "exec"), module.__dict__)
    finally:
        del sys.modules[module.__name__]
    return module.__dict__


def test_generated_python_delta_decoder_agrees_with_schema_on_every_corpus_frame() -> None:
    """The GENERATED Python decoder, not a reading of the model, against the schema."""
    ns = _exec_delta_python()
    validator = _delta_validator()
    checked = accepted = 0
    disagreements = []
    for where, frame in _delta_frames():
        for label, candidate in _perturbations(frame):
            schema_ok = validator.is_valid(candidate)
            try:
                decoded = ns["Delta"].from_wire(candidate["Delta"]) if isinstance(candidate, dict) else None
                generated_ok = decoded is not None
            except ValueError:
                generated_ok = False
            checked += 1
            accepted += schema_ok
            if schema_ok != generated_ok:
                disagreements.append(f"{where} [{label}]: schema={schema_ok} generated={generated_ok}")
            elif generated_ok:
                # What decodes re-encodes to the frame it came from, except that an
                # explicit `key: null` is the absent form and an encoder omits it.
                expected = copy.deepcopy(candidate)
                for op in expected["Delta"]["ops"]:
                    if op.get("NodeAdd", {}).get("key", "") is None:
                        del op["NodeAdd"]["key"]
                assert {"Delta": decoded.to_wire()} == expected, f"{where} [{label}] re-encode"
    assert not disagreements, "\n".join(disagreements[:20])
    assert 0 < accepted < checked
